"use client";
import Head from "next/head";
import ControlPanelModal from "@/components/ControlPanelModal/control_panel";
import TopNavbar from "@/components/TopNavbar/TopNavBar";
import ScrollToTop from "@/components/shared/ScrollToTop";
import { Inter } from "next/font/google";
import type { Metadata } from "next";
// import Sidebar from "@/components/LeftSidebar/SubMenu";
import { useState } from "react";
import SideNavbar from "@/components/sidebar/SideBarTest";
import Sidebar from "@/components/LeftSidebar/LeftSideBar";
import { usePathname, useRouter } from "next/navigation";

// import SidebarTest from "@/components/sidebar/Sidebar";
const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Lawfirm Dashboard",
//   description: "Generated by Clickers",
// };

export default function ClientLayout({
  children,
  userImageUrl,
  userName,
  userRole,
  // logout,
}: {
  children: React.ReactNode;
  userImageUrl: any;
  userName: string;
  userRole: any;
  // logout: any;
}) {
  const router = usePathname();
  const isLoginPage = router === "/login";
  const isHomePage = router === "/";

  const [active, setActive] = useState(false);

  const toggleActive = () => {
    setActive(!active);
  };
  return (
    <html lang="en">
      <Head>
        <title>Dashboard</title>
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
      </Head>

      <body className={inter.className}>
        <div className={`main-wrapper-content ${active && "active"}`}>
          {!isLoginPage && !isHomePage && (
            <>
              <TopNavbar
                toogleActive={toggleActive}
                userImageUrl={userImageUrl}
                userName={userName}
                userRole={userRole}
                // logout={logout}
              />
              <Sidebar toggleActive={toggleActive} />
            </>
          )}

          {children}
        </div>
        {/* </div> */}

        {/* ScrollToTop */}
        {!isLoginPage && !isHomePage && (
          <>
            <ScrollToTop />

            <ControlPanelModal />
          </>
        )}
      </body>
    </html>
  );
}
